"use client";

import { useEffect, useState, useCallback } from "react";
import type { Bookmark } from "@/lib/types";

type LinkNode = {
  id: string;
  url: string;
  title: string;
  domain: string;
  image?: string;
  x: number;
  y: number;
  collectionId?: string;
};

type BoardCollection = {
  id: string;
  name: string;
  description?: string;
  color: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isAutoGenerated: boolean;
  clusterType?: string;
};

type BoardDataState = {
  nodes: LinkNode[];
  collections: BoardCollection[];
};

let cachedData: BoardDataState | null = null;
let inFlightPromise: Promise<BoardDataState> | null = null;

async function fetchBoardData(): Promise<BoardDataState> {
  const bookmarksResponse = await fetch("/api/bookmarks");
  if (!bookmarksResponse.ok) {
    throw new Error("Failed to load bookmarks");
  }
  const bookmarks: Bookmark[] = await bookmarksResponse.json();

  const collectionsResponse = await fetch("/api/collections");
  if (!collectionsResponse.ok) {
    throw new Error("Failed to load collections");
  }
  const { collections }: { collections: BoardCollection[] } =
    await collectionsResponse.json();

  const nodes: LinkNode[] = bookmarks.map((bookmark) => ({
    id: bookmark.id,
    url: bookmark.url,
    title: bookmark.title || bookmark.domain,
    domain: bookmark.domain,
    image: bookmark.imageUrl ?? undefined,
    collectionId: bookmark.collectionId ?? undefined,
    x: bookmark.x,
    y: bookmark.y,
  }));

  return { nodes, collections };
}

async function loadBoardData(): Promise<BoardDataState> {
  if (cachedData) return cachedData;
  if (!inFlightPromise) {
    inFlightPromise = fetchBoardData()
      .then((data) => {
        cachedData = data;
        return data;
      })
      .finally(() => {
        inFlightPromise = null;
      });
  }
  return inFlightPromise;
}

export function useBoardData() {
  const [state, setState] = useState<BoardDataState | null>(cachedData);
  const [isLoading, setIsLoading] = useState(!cachedData);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (cachedData) {
      setState(cachedData);
      setIsLoading(false);
      return;
    }

    let cancelled = false;
    setIsLoading(true);
    loadBoardData()
      .then((data) => {
        if (!cancelled) {
          setState(data);
          setIsLoading(false);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : "Unknown error");
          setIsLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const setAndCache = useCallback(
    (updater: (prev: BoardDataState) => BoardDataState) => {
      setState((prev) => {
        const base = prev ?? { nodes: [], collections: [] };
        const next = updater(base);
        cachedData = next;
        return next;
      });
    },
    []
  );

  const refresh = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const data = await fetchBoardData();
      cachedData = data;
      setState(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setIsLoading(false);
    }
  }, []);

  const addNodeOptimistic = useCallback(
    (node: LinkNode) => {
      setAndCache((prev) => ({
        ...prev,
        nodes: [...prev.nodes, node],
      }));
    },
    [setAndCache]
  );

  const updateNodePositionOptimistic = useCallback(
    (id: string, x: number, y: number) => {
      setAndCache((prev) => ({
        ...prev,
        nodes: prev.nodes.map((n) =>
          n.id === id
            ? {
                ...n,
                x,
                y,
              }
            : n
        ),
      }));
    },
    [setAndCache]
  );

  const updateNodeMetaOptimistic = useCallback(
    (id: string, meta: Partial<Pick<LinkNode, "title" | "domain" | "image">>) => {
      setAndCache((prev) => ({
        ...prev,
        nodes: prev.nodes.map((n) =>
          n.id === id
            ? {
                ...n,
                ...meta,
              }
            : n
        ),
      }));
    },
    [setAndCache]
  );

  const deleteNodeOptimistic = useCallback(
    (id: string) => {
      setAndCache((prev) => ({
        ...prev,
        nodes: prev.nodes.filter((n) => n.id !== id),
      }));
    },
    [setAndCache]
  );

  const clearAllOptimistic = useCallback(() => {
    setAndCache((prev) => ({
      ...prev,
      nodes: [],
      collections: [],
    }));
  }, [setAndCache]);

  const addCollectionOptimistic = useCallback(
    (collection: BoardCollection) => {
      setAndCache((prev) => ({
        ...prev,
        collections: [...prev.collections, collection],
      }));
    },
    [setAndCache]
  );

  const deleteCollectionOptimistic = useCallback(
    (id: string) => {
      setAndCache((prev) => ({
        ...prev,
        collections: prev.collections.filter((c) => c.id !== id),
        nodes: prev.nodes.map((n) =>
          n.collectionId === id ? { ...n, collectionId: undefined } : n
        ),
      }));
    },
    [setAndCache]
  );

  return {
    nodes: state?.nodes ?? [],
    collections: state?.collections ?? [],
    isLoading,
    error,
    refresh,
    addNodeOptimistic,
    updateNodePositionOptimistic,
    updateNodeMetaOptimistic,
    deleteNodeOptimistic,
    clearAllOptimistic,
    addCollectionOptimistic,
    deleteCollectionOptimistic,
  };
}
