import React from "react";
import { Trash2, Settings } from "lucide-react";
import LoadingSpinner from "./loading-spinner";

type Collection = {
  id: string;
  name: string;
  description?: string;
  color: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isAutoGenerated: boolean;
  clusterType?: string;
};

type CollectionContainerProps = {
  collection: Collection;
  isSelected?: boolean;
  isDragging?: boolean;
  isDeleting?: boolean;
  onMouseDown: (e: React.MouseEvent) => void;
  onDelete: () => void;
  onEdit?: () => void;
  children?: React.ReactNode;
};

export default function CollectionContainer({
  collection,
  isSelected = false,
  isDragging = false,
  isDeleting = false,
  onMouseDown,
  onDelete,
  onEdit,
  children,
}: CollectionContainerProps) {
  return (
    <div
      className={`absolute select-none border-2 border-dashed rounded-3xl transition-all duration-300 animate-fade-in ${
        isDragging ? "z-50" : "z-5"
      } ${isSelected ? "ring-4 ring-offset-2 ring-blue-400/50" : ""}`}
      style={{
        transform: `translate(${collection.x}px, ${collection.y}px)`,
        width: collection.width,
        height: collection.height,
        borderColor: collection.color,
        backgroundColor: `${collection.color}08`, // Very transparent background
        ...(isDragging && {
          filter: "drop-shadow(0 25px 35px rgb(0 0 0 / 0.2))",
          transform: `translate(${collection.x}px, ${collection.y}px) scale(1.05)`,
        }),
      }}
    >
      {/* Collection Header */}
      <div
        className="flex items-center justify-between p-4 cursor-grab active:cursor-grabbing rounded-t-3xl backdrop-blur-sm"
        style={{
          background: `linear-gradient(135deg, ${collection.color}20 0%, ${collection.color}10 100%)`,
          borderBottom: `1px solid ${collection.color}30`,
        }}
        onMouseDown={onMouseDown}
      >
        <div className="flex-1 min-w-0">
          <h3
            className="font-bold text-base truncate"
            style={{ color: collection.color }}
            title={collection.name}
          >
            {collection.name}
          </h3>
          {collection.description && (
            <p
              className="text-sm opacity-80 truncate mt-1 font-medium"
              style={{ color: collection.color }}
              title={collection.description}
            >
              {collection.description}
            </p>
          )}
          {collection.isAutoGenerated && (
            <div className="flex items-center gap-2 mt-2">
              <div className="flex items-center gap-1 px-2 py-1 rounded-full bg-white/20 backdrop-blur-sm">
                <svg
                  className="w-3 h-3"
                  style={{ color: collection.color }}
                  fill="currentColor"
                  viewBox="0 0 20 20"
                >
                  <path
                    fillRule="evenodd"
                    d="M11.3 1.046A1 1 0 0112 2v5h4a1 1 0 01.82 1.573l-7 10A1 1 0 018 18v-5H4a1 1 0 01-.82-1.573l7-10a1 1 0 011.12-.38z"
                    clipRule="evenodd"
                  />
                </svg>
                <span
                  className="text-xs font-semibold"
                  style={{ color: collection.color }}
                >
                  AI Generated
                </span>
              </div>
            </div>
          )}
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-1 ml-2">
          {onEdit && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onEdit();
              }}
              className="p-1 rounded opacity-60 hover:opacity-100 transition-opacity"
              style={{ color: collection.color }}
              title="Edit collection"
            >
              <Settings size={14} />
            </button>
          )}

          <button
            onClick={(e) => {
              e.stopPropagation();
              onDelete();
            }}
            disabled={isDeleting}
            className="p-1 rounded opacity-60 hover:opacity-100 disabled:opacity-30 transition-opacity"
            style={{ color: collection.color }}
            title="Delete collection"
          >
            {isDeleting ? <LoadingSpinner size="sm" /> : <Trash2 size={14} />}
          </button>
        </div>
      </div>

      {/* Collection Content Area */}
      <div className="p-2 h-full">{children}</div>

      {/* Resize handle (optional for future enhancement) */}
      <div
        className="absolute bottom-0 right-0 w-4 h-4 cursor-se-resize opacity-0 hover:opacity-50 transition-opacity"
        style={{ backgroundColor: collection.color }}
      />
    </div>
  );
}
