// lib/clustering.ts
import { db } from "@/db/client";
import { bookmarks, collections } from "@/db/schema";
import { eq } from "drizzle-orm";
import { nanoid } from "nanoid";

export type LinkNode = {
  id: string;
  url: string;
  title: string;
  domain: string;
  description?: string;
  image?: string;
  x: number;
  y: number;
  collectionId?: string;
  createdAt: Date;
};

export type Collection = {
  id: string;
  boardId: string;
  name: string;
  description?: string;
  color: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isAutoGenerated: boolean;
  clusterType?: string;
  createdAt: Date;
};

export type ClusterSuggestion = {
  type: "domain" | "content" | "keywords";
  name: string;
  description: string;
  bookmarkIds: string[];
  confidence: number;
  suggestedPosition: { x: number; y: number };
  color: string;
};

/**
 * Generate smart clustering suggestions for uncollected bookmarks
 */
export async function generateClusterSuggestions(
  boardId: string,
  bookmarkNodes: LinkNode[]
): Promise<ClusterSuggestion[]> {
  const uncollectedBookmarks = bookmarkNodes.filter(
    (node) => !node.collectionId
  );

  if (uncollectedBookmarks.length < 2) {
    return [];
  }

  const suggestions: ClusterSuggestion[] = [];

  // 1. Domain-based clustering
  const domainGroups = groupByDomain(uncollectedBookmarks);
  suggestions.push(...domainGroups);

  // 2. Content similarity clustering
  const contentGroups = await groupByContentSimilarity(uncollectedBookmarks);
  suggestions.push(...contentGroups);

  // 3. Keyword-based clustering
  const keywordGroups = groupByKeywords(uncollectedBookmarks);
  suggestions.push(...keywordGroups);

  // Sort by confidence and return top suggestions
  return suggestions
    .filter((s) => s.confidence > 0.6 && s.bookmarkIds.length >= 2)
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 8); // Limit to 8 suggestions
}

/**
 * Group bookmarks by domain
 */
function groupByDomain(bookmarks: LinkNode[]): ClusterSuggestion[] {
  const domainMap = new Map<string, LinkNode[]>();

  bookmarks.forEach((bookmark) => {
    const domain = bookmark.domain;
    if (!domainMap.has(domain)) {
      domainMap.set(domain, []);
    }
    domainMap.get(domain)!.push(bookmark);
  });

  const suggestions: ClusterSuggestion[] = [];
  const colors = [
    "#6366f1",
    "#8b5cf6",
    "#ec4899",
    "#ef4444",
    "#f59e0b",
    "#10b981",
    "#06b6d4",
  ];

  domainMap.forEach((domainBookmarks, domain) => {
    if (domainBookmarks.length >= 2) {
      // Calculate center position
      const centerX =
        domainBookmarks.reduce((sum, b) => sum + b.x, 0) /
        domainBookmarks.length;
      const centerY =
        domainBookmarks.reduce((sum, b) => sum + b.y, 0) /
        domainBookmarks.length;

      suggestions.push({
        type: "domain",
        name: `${domain} Links`,
        description: `${domainBookmarks.length} bookmarks from ${domain}`,
        bookmarkIds: domainBookmarks.map((b) => b.id),
        confidence: Math.min(0.9, 0.6 + domainBookmarks.length * 0.1),
        suggestedPosition: { x: Math.round(centerX), y: Math.round(centerY) },
        color: colors[suggestions.length % colors.length],
      });
    }
  });

  return suggestions;
}

/**
 * Group bookmarks by content similarity using title and description analysis
 */
async function groupByContentSimilarity(
  bookmarks: LinkNode[]
): Promise<ClusterSuggestion[]> {
  if (bookmarks.length < 2) return [];

  const suggestions: ClusterSuggestion[] = [];
  const colors = ["#ec4899", "#8b5cf6", "#06b6d4", "#10b981", "#f59e0b"];

  // Simple keyword extraction and similarity matching
  const bookmarkKeywords = bookmarks.map((bookmark) => ({
    bookmark,
    keywords: extractKeywords(bookmark.title, bookmark.description),
  }));

  // Find groups with similar keywords
  const processed = new Set<string>();

  bookmarkKeywords.forEach(
    ({ bookmark: bookmark1, keywords: keywords1 }, i) => {
      if (processed.has(bookmark1.id)) return;

      const similarBookmarks = [bookmark1];
      const commonKeywords = new Set(keywords1);

      bookmarkKeywords
        .slice(i + 1)
        .forEach(({ bookmark: bookmark2, keywords: keywords2 }) => {
          if (processed.has(bookmark2.id)) return;

          const similarity = calculateKeywordSimilarity(keywords1, keywords2);
          if (similarity > 0.3) {
            similarBookmarks.push(bookmark2);
            // Add overlapping keywords
            keywords2.forEach((k) => {
              if (keywords1.includes(k)) {
                commonKeywords.add(k);
              }
            });
          }
        });

      if (similarBookmarks.length >= 2) {
        similarBookmarks.forEach((b) => processed.add(b.id));

        const centerX =
          similarBookmarks.reduce((sum, b) => sum + b.x, 0) /
          similarBookmarks.length;
        const centerY =
          similarBookmarks.reduce((sum, b) => sum + b.y, 0) /
          similarBookmarks.length;

        const topKeywords = Array.from(commonKeywords).slice(0, 2);

        suggestions.push({
          type: "content",
          name:
            topKeywords.length > 0
              ? `${topKeywords.join(" & ")} Collection`
              : "Related Content",
          description: `${similarBookmarks.length} bookmarks with similar content`,
          bookmarkIds: similarBookmarks.map((b) => b.id),
          confidence: Math.min(0.85, 0.5 + similarBookmarks.length * 0.1),
          suggestedPosition: { x: Math.round(centerX), y: Math.round(centerY) },
          color: colors[suggestions.length % colors.length],
        });
      }
    }
  );

  return suggestions;
}

/**
 * Group bookmarks by common keywords in titles
 */
function groupByKeywords(bookmarks: LinkNode[]): ClusterSuggestion[] {
  const suggestions: ClusterSuggestion[] = [];
  const colors = ["#10b981", "#f59e0b", "#ef4444", "#8b5cf6"];

  // Extract all keywords and find common ones
  const allKeywords = new Map<string, LinkNode[]>();

  bookmarks.forEach((bookmark) => {
    const keywords = extractKeywords(bookmark.title, bookmark.description);
    keywords.forEach((keyword) => {
      if (!allKeywords.has(keyword)) {
        allKeywords.set(keyword, []);
      }
      allKeywords.get(keyword)!.push(bookmark);
    });
  });

  // Find keywords that appear in multiple bookmarks
  allKeywords.forEach((keywordBookmarks, keyword) => {
    if (keywordBookmarks.length >= 2 && keyword.length > 3) {
      const centerX =
        keywordBookmarks.reduce((sum, b) => sum + b.x, 0) /
        keywordBookmarks.length;
      const centerY =
        keywordBookmarks.reduce((sum, b) => sum + b.y, 0) /
        keywordBookmarks.length;

      suggestions.push({
        type: "keywords",
        name: `${
          keyword.charAt(0).toUpperCase() + keyword.slice(1)
        } Collection`,
        description: `${keywordBookmarks.length} bookmarks about ${keyword}`,
        bookmarkIds: keywordBookmarks.map((b) => b.id),
        confidence: Math.min(0.8, 0.4 + keywordBookmarks.length * 0.1),
        suggestedPosition: { x: Math.round(centerX), y: Math.round(centerY) },
        color: colors[suggestions.length % colors.length],
      });
    }
  });

  return suggestions;
}

/**
 * Extract keywords from title and description
 */
function extractKeywords(title?: string, description?: string): string[] {
  const text = `${title || ""} ${description || ""}`.toLowerCase();

  // Common stop words to filter out
  const stopWords = new Set([
    "the",
    "a",
    "an",
    "and",
    "or",
    "but",
    "in",
    "on",
    "at",
    "to",
    "for",
    "of",
    "with",
    "by",
    "how",
    "what",
    "when",
    "where",
    "why",
    "who",
    "which",
    "this",
    "that",
    "these",
    "those",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "can",
    "must",
    "shall",
  ]);

  return text
    .replace(/[^\w\s]/g, " ") // Remove punctuation
    .split(/\s+/)
    .filter((word) => word.length > 2 && !stopWords.has(word))
    .filter((word, index, arr) => arr.indexOf(word) === index) // Remove duplicates
    .slice(0, 10); // Limit to 10 keywords
}

/**
 * Calculate similarity between two keyword arrays
 */
function calculateKeywordSimilarity(
  keywords1: string[],
  keywords2: string[]
): number {
  const set1 = new Set(keywords1);
  const set2 = new Set(keywords2);

  const intersection = new Set([...set1].filter((x) => set2.has(x)));
  const union = new Set([...set1, ...set2]);

  return union.size > 0 ? intersection.size / union.size : 0;
}

/**
 * Calculate optimal collection dimensions based on bookmarks
 */
function calculateCollectionDimensions(
  bookmarkIds: string[],
  bookmarks: LinkNode[]
) {
  if (bookmarkIds.length === 0) {
    return { width: 400, height: 300, x: 0, y: 0 };
  }

  const collectionBookmarks = bookmarks.filter((b) =>
    bookmarkIds.includes(b.id)
  );

  if (collectionBookmarks.length === 0) {
    return { width: 400, height: 300, x: 0, y: 0 };
  }

  // Calculate bounding box of bookmarks
  const bookmarkWidth = 264; // Width of bookmark cards (w-64 = 256px + padding)
  const bookmarkHeight = 200; // Approximate height of bookmark cards
  const padding = 40; // Padding around bookmarks
  const headerHeight = 80; // Collection header height

  const minX = Math.min(...collectionBookmarks.map((b) => b.x));
  const maxX = Math.max(...collectionBookmarks.map((b) => b.x));
  const minY = Math.min(...collectionBookmarks.map((b) => b.y));
  const maxY = Math.max(...collectionBookmarks.map((b) => b.y));

  // Calculate dimensions with some padding
  const width = Math.max(400, maxX - minX + bookmarkWidth + padding * 2);
  const height = Math.max(
    300,
    maxY - minY + bookmarkHeight + headerHeight + padding * 2
  );

  // Position collection to contain all bookmarks
  const x = minX - padding;
  const y = minY - headerHeight - padding;

  return { width, height, x, y };
}

/**
 * Create a collection from a cluster suggestion
 */
export async function createCollectionFromSuggestion(
  suggestion: ClusterSuggestion,
  boardId: string,
  allBookmarks?: LinkNode[]
): Promise<Collection> {
  const collectionId = nanoid();

  // Calculate optimal dimensions if bookmarks are provided
  let dimensions = {
    width: 400,
    height: 300,
    x: suggestion.suggestedPosition.x - 200,
    y: suggestion.suggestedPosition.y - 150,
  };

  if (allBookmarks && allBookmarks.length > 0) {
    dimensions = calculateCollectionDimensions(
      suggestion.bookmarkIds,
      allBookmarks
    );
  }

  // Create the collection
  const [collection] = await db
    .insert(collections)
    .values({
      id: collectionId,
      boardId,
      name: suggestion.name,
      description: suggestion.description,
      color: suggestion.color,
      x: dimensions.x,
      y: dimensions.y,
      width: dimensions.width,
      height: dimensions.height,
      isAutoGenerated: true,
      clusterType: suggestion.type,
    })
    .returning();

  // Assign bookmarks to the collection
  if (suggestion.bookmarkIds.length > 0) {
    await Promise.all(
      suggestion.bookmarkIds.map((bookmarkId) =>
        db
          .update(bookmarks)
          .set({ collectionId })
          .where(eq(bookmarks.id, bookmarkId))
      )
    );
  }

  return {
    id: collection.id,
    boardId: collection.boardId,
    name: collection.name,
    description: collection.description || undefined,
    color: collection.color || "#6366f1",
    x: collection.x,
    y: collection.y,
    width: collection.width,
    height: collection.height,
    isAutoGenerated: collection.isAutoGenerated,
    clusterType: collection.clusterType || undefined,
    createdAt: collection.createdAt,
  };
}

/**
 * Get all collections for a board
 */
export async function getBoardCollections(
  boardId: string
): Promise<Collection[]> {
  const boardCollections = await db
    .select()
    .from(collections)
    .where(eq(collections.boardId, boardId));

  return boardCollections.map((c) => ({
    id: c.id,
    boardId: c.boardId,
    name: c.name,
    description: c.description || undefined,
    color: c.color || "#6366f1",
    x: c.x,
    y: c.y,
    width: c.width,
    height: c.height,
    isAutoGenerated: c.isAutoGenerated,
    clusterType: c.clusterType || undefined,
    createdAt: c.createdAt,
  }));
}

/**
 * Delete a specific collection and remove bookmark assignments
 */
export async function deleteCollection(collectionId: string): Promise<void> {
  // First, remove collection assignments from bookmarks
  await db
    .update(bookmarks)
    .set({ collectionId: null })
    .where(eq(bookmarks.collectionId, collectionId));

  // Then delete the collection
  await db.delete(collections).where(eq(collections.id, collectionId));
}

/**
 * Delete all collections for a board and remove all bookmark assignments
 */
export async function clearBoardCollections(boardId: string): Promise<void> {
  // First, remove all collection assignments from bookmarks in this board
  await db
    .update(bookmarks)
    .set({ collectionId: null })
    .where(eq(bookmarks.boardId, boardId));

  // Then delete all collections for this board
  await db.delete(collections).where(eq(collections.boardId, boardId));
}
