"use client";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import ConfirmationDialog from "@/components/ui/confirmation-dialog";
import LoadingSpinner from "@/components/ui/loading-spinner";
import ShareButton from "@/components/ui/share-button";
import CollectionContainer from "@/components/ui/collection-container";
import ClusteringSuggestionsDialog from "@/components/ui/clustering-suggestions-dialog";

type LinkNode = {
  id: string;
  url: string;
  title: string;
  domain: string;
  image?: string;
  x: number;
  y: number;
  collectionId?: string;
};

type Collection = {
  id: string;
  name: string;
  description?: string;
  color: string;
  x: number;
  y: number;
  width: number;
  height: number;
  isAutoGenerated: boolean;
  clusterType?: string;
};

type ClusterSuggestion = {
  type: "domain" | "content" | "keywords";
  name: string;
  description: string;
  bookmarkIds: string[];
  confidence: number;
  suggestedPosition: { x: number; y: number };
  color: string;
};

const BOARD_SIZE = 20000;
const clamp = (n: number, min: number, max: number) =>
  Math.max(min, Math.min(max, n));

// Real page thumbnail (Chrome-like preview) via Microlink
function previewImageUrl(u: string) {
  const base = "https://api.microlink.io";
  const qs = new URLSearchParams({
    url: u,
    screenshot: "true",
    meta: "false",
    embed: "screenshot.url",
    "viewport.width": "1200",
    "viewport.height": "630",
  });
  return `${base}/?${qs.toString()}`;
}

// Quick fallback for domain/title from the URL itself
function urlToPreview(u: string) {
  try {
    const parsed = new URL(u);
    const domain = parsed.hostname.replace(/^www\./, "");
    const path =
      parsed.pathname && parsed.pathname !== "/"
        ? decodeURIComponent(parsed.pathname.replace(/\/$/, ""))
        : "";
    const title = path.split("/").filter(Boolean).slice(-1)[0] || domain || u;
    return { domain, title };
  } catch {
    return { domain: u, title: u };
  }
}

export default function Board2D() {
  const [nodes, setNodes] = useState<LinkNode[]>([]);
  const [collections, setCollections] = useState<Collection[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isAddingBookmark, setIsAddingBookmark] = useState(false);
  const [isClearingBookmarks, setIsClearingBookmarks] = useState(false);
  const [isUpdatingPosition, setIsUpdatingPosition] = useState<string | null>(
    null
  );
  const [isEnriching, setIsEnriching] = useState<string | null>(null);
  const [isDeletingBookmark, setIsDeletingBookmark] = useState<string | null>(
    null
  );
  const [draggedNodeId, setDraggedNodeId] = useState<string | null>(null);

  // Collections and clustering state
  const [clusterSuggestions, setClusterSuggestions] = useState<
    ClusterSuggestion[]
  >([]);
  const [isClusteringDialogOpen, setIsClusteringDialogOpen] = useState(false);
  const [isLoadingSuggestions, setIsLoadingSuggestions] = useState(false);
  const [draggedCollectionId, setDraggedCollectionId] = useState<string | null>(
    null
  );
  const [isDeletingCollection, setIsDeletingCollection] = useState<
    string | null
  >(null);

  // Confirmation dialog state
  const [confirmDialog, setConfirmDialog] = useState<{
    isOpen: boolean;
    title: string;
    description: string;
    onConfirm: () => void;
  }>({
    isOpen: false,
    title: "",
    description: "",
    onConfirm: () => {},
  });

  // Load bookmarks and collections from database on component mount
  useEffect(() => {
    async function loadData() {
      try {
        // Load bookmarks
        const bookmarksResponse = await fetch("/api/bookmarks");
        if (bookmarksResponse.ok) {
          const bookmarks = await bookmarksResponse.json();
          setNodes(
            bookmarks.map(
              (bookmark: {
                id: string;
                url: string;
                title: string | null;
                domain: string;
                imageUrl: string | null;
                collectionId: string | null;
                x: number;
                y: number;
              }) => ({
                id: bookmark.id,
                url: bookmark.url,
                title: bookmark.title || bookmark.domain,
                domain: bookmark.domain,
                image: bookmark.imageUrl,
                collectionId: bookmark.collectionId || undefined,
                x: bookmark.x,
                y: bookmark.y,
              })
            )
          );

          // Load collections
          const collectionsResponse = await fetch("/api/collections");
          if (collectionsResponse.ok) {
            const { collections: collectionsData } =
              await collectionsResponse.json();
            setCollections(collectionsData || []);
          }

          toast.success(
            `Loaded ${bookmarks.length} bookmark${
              bookmarks.length !== 1 ? "s" : ""
            }`
          );
        } else {
          toast.error("Failed to load bookmarks");
        }
      } catch (error) {
        console.error("Failed to load data:", error);
        toast.error("Failed to load data");
      } finally {
        setIsLoading(false);
      }
    }
    loadData();
  }, []);

  // Cleanup event listeners on unmount
  useEffect(() => {
    return () => {
      document.removeEventListener("mousemove", onNodeDragMove);
      document.removeEventListener("mouseup", onNodeDragEnd);
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
    };
  }, []);

  const [url, setUrl] = useState("");

  const wrapperRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const [scale, setScale] = useState(1);
  const [offset, setOffset] = useState({ x: 0, y: 0 });

  const isPanningRef = useRef(false);
  const panStartRef = useRef({ x: 0, y: 0 });
  const offsetStartRef = useRef({ x: 0, y: 0 });

  const draggingIdRef = useRef<string | null>(null);
  const dragStartRef = useRef({ x: 0, y: 0 });
  const nodeStartRef = useRef({ x: 0, y: 0 });

  const screenToBoard = useCallback(
    (px: number, py: number) => ({
      x: (px - offset.x) / scale,
      y: (py - offset.y) / scale,
    }),
    [offset.x, offset.y, scale]
  );

  // Center view on the board once
  useEffect(() => {
    const el = wrapperRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    setOffset({
      x: rect.width / 2 - BOARD_SIZE / 2,
      y: rect.height / 2 - BOARD_SIZE / 2,
    });
  }, []);

  // Paste to populate input field
  useEffect(() => {
    function onPaste(e: ClipboardEvent) {
      const text = e.clipboardData?.getData("text");
      if (!text) return;
      try {
        const url = new URL(text.trim()).toString();
        setUrl(url);
      } catch {}
    }
    window.addEventListener("paste", onPaste);
    return () => window.removeEventListener("paste", onPaste);
  }, []);

  // Zoom
  useEffect(() => {
    const el = wrapperRef.current;
    if (!el) return;
    function onWheel(e: WheelEvent) {
      e.preventDefault();
      const currentEl = wrapperRef.current;
      if (!currentEl) return;
      const rect = currentEl.getBoundingClientRect();
      const mouse = { x: e.clientX - rect.left, y: e.clientY - rect.top };
      const before = screenToBoard(mouse.x, mouse.y);
      const next = clamp(scale * (e.deltaY < 0 ? 1.1 : 0.9), 0.3, 2.5);
      setScale(next);
      setOffset({ x: mouse.x - before.x * next, y: mouse.y - before.y * next });
    }
    el.addEventListener("wheel", onWheel, { passive: false });
    return () => el.removeEventListener("wheel", onWheel);
  }, [scale, offset, screenToBoard]);

  // Pan (only when clicking the blank board)
  function onPanStart(e: React.MouseEvent) {
    // Don't pan if we're dragging a node
    if (draggingIdRef.current) return;
    if (e.target !== contentRef.current) return;

    isPanningRef.current = true;
    panStartRef.current = { x: e.clientX, y: e.clientY };
    offsetStartRef.current = { ...offset };

    // Add cursor style
    document.body.style.cursor = "grabbing";
  }

  function onPanMove(e: React.MouseEvent) {
    if (!isPanningRef.current) return;
    setOffset({
      x: offsetStartRef.current.x + (e.clientX - panStartRef.current.x),
      y: offsetStartRef.current.y + (e.clientY - panStartRef.current.y),
    });
  }

  function onPanEnd() {
    if (isPanningRef.current) {
      isPanningRef.current = false;
      document.body.style.cursor = "";
    }
  }

  // Drag nodes
  function onNodeDragStart(id: string, e: React.MouseEvent) {
    e.stopPropagation();
    e.preventDefault();

    draggingIdRef.current = id;
    setDraggedNodeId(id);
    dragStartRef.current = { x: e.clientX, y: e.clientY };
    const n = nodes.find((n) => n.id === id)!;
    nodeStartRef.current = { x: n.x, y: n.y };

    // Add cursor style and prevent text selection
    document.body.style.cursor = "grabbing";
    document.body.style.userSelect = "none";

    // Add event listeners
    document.addEventListener("mousemove", onNodeDragMove, { passive: false });
    document.addEventListener("mouseup", onNodeDragEnd, { once: true });
  }

  function onNodeDragMove(e: MouseEvent) {
    e.preventDefault();
    const id = draggingIdRef.current;
    if (!id) return;

    const dx = (e.clientX - dragStartRef.current.x) / scale;
    const dy = (e.clientY - dragStartRef.current.y) / scale;
    const newX = Math.round(nodeStartRef.current.x + dx);
    const newY = Math.round(nodeStartRef.current.y + dy);

    setNodes((curr) =>
      curr.map((n) =>
        n.id === id
          ? {
              ...n,
              x: newX,
              y: newY,
            }
          : n
      )
    );
  }

  async function onNodeDragEnd(e: MouseEvent) {
    e.preventDefault();
    const id = draggingIdRef.current;

    // Clean up cursor and event listeners first
    document.body.style.cursor = "";
    document.body.style.userSelect = "";
    document.removeEventListener("mousemove", onNodeDragMove);
    setDraggedNodeId(null);

    if (id) {
      const node = nodes.find((n) => n.id === id);
      if (node) {
        setIsUpdatingPosition(id);
        try {
          const response = await fetch(`/api/bookmarks/${id}`, {
            method: "PATCH",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ x: node.x, y: node.y }),
          });

          if (response.ok) {
            toast.success("Position saved");
          } else {
            toast.error("Failed to save position");
          }
        } catch (error) {
          console.error("Failed to save bookmark position:", error);
          toast.error("Failed to save position");
        } finally {
          setIsUpdatingPosition(null);
        }
      }
    }
    draggingIdRef.current = null;
  }

  // Add a link node (with real visual thumbnail)
  async function addUrl(u: string) {
    const el = wrapperRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const center = screenToBoard(rect.width / 2, rect.height / 2);

    const { domain, title } = urlToPreview(u);
    const x = Math.round(center.x);
    const y = Math.round(center.y);

    setIsAddingBookmark(true);
    try {
      // Create bookmark in database
      const response = await fetch("/api/bookmarks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          url: u,
          domain,
          title,
          x,
          y,
          imageUrl: previewImageUrl(u),
        }),
      });

      if (response.ok) {
        const bookmark = await response.json();
        const newNode: LinkNode = {
          id: bookmark.id,
          url: bookmark.url,
          title: bookmark.title || domain,
          domain: bookmark.domain,
          image: bookmark.imageUrl,
          x: bookmark.x,
          y: bookmark.y,
        };

        setNodes((n) => [...n, newNode]);
        toast.success("Bookmark added successfully!");

        // Optional: upgrade title/desc/image via your /api/scrape route
        enrichNode(bookmark.id, u);
      } else {
        toast.error("Failed to create bookmark");
      }
    } catch (error) {
      console.error("Error creating bookmark:", error);
      toast.error("Failed to create bookmark");
    } finally {
      setIsAddingBookmark(false);
    }
  }

  async function enrichNode(id: string, link: string) {
    setIsEnriching(id);
    try {
      const res = await fetch(`/api/scrape?url=${encodeURIComponent(link)}`);
      const meta = await res.json();

      // Update local state
      setNodes((curr) =>
        curr.map((n) =>
          n.id === id
            ? {
                ...n,
                title: meta.title ?? n.title,
                domain: meta.domain ?? n.domain,
                image: meta.imageUrl ?? n.image, // keep screenshot if OG missing
              }
            : n
        )
      );

      // Update database with enriched metadata
      try {
        const response = await fetch(`/api/bookmarks/${id}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            title: meta.title,
            description: meta.description,
            imageUrl: meta.imageUrl,
          }),
        });

        if (response.ok) {
          toast.success("Bookmark metadata updated");
        }
      } catch (error) {
        console.error("Failed to update bookmark metadata:", error);
        toast.error("Failed to update bookmark metadata");
      }
    } catch (error) {
      console.error("Failed to enrich bookmark:", error);
      toast.error("Failed to enrich bookmark");
    } finally {
      setIsEnriching(null);
    }
  }

  // Clustering functions
  async function loadClusterSuggestions() {
    setIsLoadingSuggestions(true);
    try {
      const response = await fetch("/api/collections?action=suggestions");
      if (response.ok) {
        const { suggestions } = await response.json();
        setClusterSuggestions(suggestions || []);
      } else {
        toast.error("Failed to load clustering suggestions");
      }
    } catch (error) {
      console.error("Failed to load clustering suggestions:", error);
      toast.error("Failed to load clustering suggestions");
    } finally {
      setIsLoadingSuggestions(false);
    }
  }

  async function acceptClusterSuggestion(suggestion: ClusterSuggestion) {
    try {
      const response = await fetch("/api/collections", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          action: "create-from-suggestion",
          suggestion,
        }),
      });

      if (response.ok) {
        const { collection } = await response.json();
        setCollections((prev) => [...prev, collection]);

        // Update nodes to reflect the new collection assignment
        setNodes((prev) =>
          prev.map((node) =>
            suggestion.bookmarkIds.includes(node.id)
              ? { ...node, collectionId: collection.id }
              : node
          )
        );

        // Remove the accepted suggestion
        setClusterSuggestions((prev) => prev.filter((s) => s !== suggestion));

        toast.success(`Created collection "${collection.name}"`);
      } else {
        toast.error("Failed to create collection");
      }
    } catch (error) {
      console.error("Failed to create collection:", error);
      toast.error("Failed to create collection");
    }
  }

  function openClusteringDialog() {
    setIsClusteringDialogOpen(true);
    loadClusterSuggestions();
  }

  function recenter() {
    const el = wrapperRef.current;
    if (!el) return;
    const rect = el.getBoundingClientRect();
    setScale(1);
    setOffset({
      x: rect.width / 2 - BOARD_SIZE / 2,
      y: rect.height / 2 - BOARD_SIZE / 2,
    });
  }

  function showClearConfirmation() {
    setConfirmDialog({
      isOpen: true,
      title: "Clear All Bookmarks & Collections",
      description:
        "Are you sure you want to delete all bookmarks and collections? This action cannot be undone.",
      onConfirm: clearAllBookmarks,
    });
  }

  function showDeleteBookmarkConfirmation(
    bookmarkId: string,
    bookmarkTitle: string
  ) {
    setConfirmDialog({
      isOpen: true,
      title: "Delete Bookmark",
      description: `Are you sure you want to delete "${bookmarkTitle}"? This action cannot be undone.`,
      onConfirm: () => deleteBookmark(bookmarkId),
    });
  }

  async function clearAllBookmarks() {
    setIsClearingBookmarks(true);
    try {
      const response = await fetch("/api/bookmarks/clear", {
        method: "DELETE",
      });
      if (response.ok) {
        setNodes([]);
        setCollections([]); // Clear collections when clearing all bookmarks
        toast.success("All bookmarks and collections cleared");
      } else {
        toast.error("Failed to clear bookmarks");
      }
    } catch (error) {
      console.error("Error clearing bookmarks:", error);
      toast.error("Failed to clear bookmarks");
    } finally {
      setIsClearingBookmarks(false);
    }
  }

  async function deleteBookmark(bookmarkId: string) {
    setIsDeletingBookmark(bookmarkId);
    try {
      const response = await fetch(`/api/bookmarks/${bookmarkId}`, {
        method: "DELETE",
      });
      if (response.ok) {
        setNodes((prev) => prev.filter((node) => node.id !== bookmarkId));
        toast.success("Bookmark deleted");
      } else {
        toast.error("Failed to delete bookmark");
      }
    } catch (error) {
      console.error("Error deleting bookmark:", error);
      toast.error("Failed to delete bookmark");
    } finally {
      setIsDeletingBookmark(null);
    }
  }

  function showDeleteCollectionConfirmation(
    collectionId: string,
    collectionName: string
  ) {
    setConfirmDialog({
      isOpen: true,
      title: "Delete Collection",
      description: `Are you sure you want to delete the collection "${collectionName}"? Bookmarks will be uncollected but not deleted.`,
      onConfirm: () => deleteCollection(collectionId),
    });
  }

  async function deleteCollection(collectionId: string) {
    setIsDeletingCollection(collectionId);
    try {
      const response = await fetch(`/api/collections?id=${collectionId}`, {
        method: "DELETE",
      });
      if (response.ok) {
        // Remove collection from state
        setCollections((prev) => prev.filter((c) => c.id !== collectionId));

        // Update nodes to remove collection assignment
        setNodes((prev) =>
          prev.map((node) =>
            node.collectionId === collectionId
              ? { ...node, collectionId: undefined }
              : node
          )
        );

        toast.success("Collection deleted");
      } else {
        toast.error("Failed to delete collection");
      }
    } catch (error) {
      console.error("Error deleting collection:", error);
      toast.error("Failed to delete collection");
    } finally {
      setIsDeletingCollection(null);
    }
  }

  if (isLoading) {
    return (
      <div className="h-full w-full bg-gradient-to-br from-slate-50 via-white to-indigo-50 flex items-center justify-center">
        <div className="text-center animate-fade-in">
          <div className="relative mb-8">
            <div className="w-16 h-16 mx-auto">
              <div className="absolute inset-0 rounded-full border-4 border-indigo-200"></div>
              <div className="absolute inset-0 rounded-full border-4 border-indigo-600 border-t-transparent animate-spin"></div>
            </div>
          </div>
          <div className="text-xl font-semibold text-slate-900 mb-2">
            Loading your workspace
          </div>
          <div className="text-sm text-slate-500">
            Preparing your infinite canvas...
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full w-full bg-gradient-to-br from-slate-50 via-white to-indigo-50 text-slate-900">
      {/* hint */}
      {/* <div className="pointer-events-none fixed left-4 top-4 z-50 rounded-xl border border-zinc-200 bg-white/90 p-3 text-xs text-zinc-700 shadow">
        <div className="font-semibold">Linkyard – 2D Board</div>
        <div>
          Paste or type a URL • Press Enter or click Add • Drag cards • Wheel to
          zoom • Drag background to pan
        </div>
      </div> */}

      {/* controls */}
      <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 glass rounded-3xl border border-white/20 p-3 shadow-modern-lg backdrop-blur-xl">
        <div className="flex items-center gap-3">
          <input
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            onKeyDown={async (e) => {
              if (e.key === "Enter" && url) {
                await addUrl(url);
                setUrl("");
              }
            }}
            placeholder="Paste or type a link…"
            className="w-[420px] rounded-2xl border border-white/30 bg-white/80 backdrop-blur-sm px-4 py-3 text-sm placeholder:text-slate-400 focus-modern transition-all duration-200 hover:bg-white/90"
          />
          <button
            onClick={async () => {
              if (url) {
                await addUrl(url);
                setUrl("");
              }
            }}
            disabled={isAddingBookmark || !url}
            className="btn-gradient rounded-2xl px-5 py-3 text-sm font-semibold text-white disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:transform-none flex items-center gap-2 shadow-modern"
          >
            {isAddingBookmark ? (
              <>
                <LoadingSpinner size="sm" />
                Adding...
              </>
            ) : (
              "Add"
            )}
          </button>
          <button
            onClick={recenter}
            className="rounded-2xl border border-white/30 bg-white/60 backdrop-blur-sm px-4 py-3 text-sm font-medium text-slate-700 hover:bg-white/80 transition-all duration-200 hover:scale-105"
          >
            <svg
              className="w-4 h-4 mr-2"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
              />
            </svg>
            Recenter
          </button>
          <button
            onClick={showClearConfirmation}
            disabled={isClearingBookmarks || nodes.length === 0}
            className="rounded-2xl border border-red-200/50 bg-red-50/80 backdrop-blur-sm px-4 py-3 text-sm font-medium text-red-700 hover:bg-red-100/80 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 transition-all duration-200 hover:scale-105 flex items-center gap-2"
          >
            {isClearingBookmarks ? (
              <>
                <LoadingSpinner size="sm" />
                Clearing...
              </>
            ) : (
              <>
                <svg
                  className="w-4 h-4"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
                Clear
              </>
            )}
          </button>
          <button
            onClick={openClusteringDialog}
            disabled={nodes.length < 2}
            className="rounded-2xl bg-gradient-to-r from-purple-500 to-indigo-600 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100 transition-all duration-200 hover:scale-105 shadow-modern flex items-center gap-2"
            title="Smart organize your bookmarks"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M12 2L2 7l10 5 10-5-10-5z" />
              <path d="M2 17l10 5 10-5" />
              <path d="M2 12l10 5 10-5" />
            </svg>
            Cluster
          </button>
          <ShareButton />
        </div>
      </div>

      {/* board */}
      <div
        ref={wrapperRef}
        className="h-full w-full overflow-hidden"
        onMouseDown={onPanStart}
        onMouseMove={onPanMove}
        onMouseUp={onPanEnd}
      >
        <div
          ref={contentRef}
          className="relative"
          style={{
            width: BOARD_SIZE,
            height: BOARD_SIZE,
            transform: `translate(${offset.x}px, ${offset.y}px) scale(${scale})`,
            transformOrigin: "0 0",
            background: "#fff",
          }}
        >
          {/* Render collections first (background layer) */}
          {collections.map((collection) => (
            <CollectionContainer
              key={collection.id}
              collection={collection}
              isSelected={false}
              isDragging={draggedCollectionId === collection.id}
              isDeleting={isDeletingCollection === collection.id}
              onMouseDown={(e) => {
                // TODO: Implement collection dragging
                e.stopPropagation();
              }}
              onDelete={() => {
                showDeleteCollectionConfirmation(
                  collection.id,
                  collection.name
                );
              }}
            />
          ))}

          {/* Render bookmarks (foreground layer) */}
          {nodes.map((n) => (
            <div
              key={n.id}
              className={`absolute transition-all duration-200 ${
                draggedNodeId === n.id ? "z-50" : "z-10"
              }`}
              style={{
                transform: `translate(${n.x}px, ${n.y}px)`,
                ...(draggedNodeId === n.id && {
                  filter: "drop-shadow(0 20px 25px rgb(0 0 0 / 0.15))",
                }),
              }}
            >
              <div
                onMouseDown={(e) => onNodeDragStart(n.id, e)}
                className="w-64 select-none rounded-3xl border border-white/20 bg-white/90 backdrop-blur-xl p-4 text-left shadow-modern-lg hover:shadow-xl cursor-grab active:cursor-grabbing relative transition-all duration-300 hover:scale-105 animate-fade-in"
              >
                {/* Delete button */}
                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    showDeleteBookmarkConfirmation(n.id, n.title);
                  }}
                  disabled={isDeletingBookmark === n.id}
                  className="absolute -top-3 -right-3 w-8 h-8 bg-gradient-to-r from-red-500 to-pink-500 hover:from-red-600 hover:to-pink-600 text-white rounded-full flex items-center justify-center text-xs font-bold disabled:opacity-50 disabled:cursor-not-allowed shadow-modern hover:shadow-lg transition-all duration-200 z-10 hover:scale-110"
                  title="Delete bookmark"
                >
                  {isDeletingBookmark === n.id ? (
                    <LoadingSpinner size="sm" />
                  ) : (
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  )}
                </button>
                {/* Visual preview */}
                <div className="mb-3 w-full overflow-hidden rounded-2xl bg-gradient-to-br from-slate-100 to-slate-200 shadow-inner">
                  <div className="aspect-[16/9] w-full relative group">
                    {n.image ? (
                      <img
                        src={n.image}
                        className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                        alt=""
                        onError={(e) => {
                          (
                            e.currentTarget as HTMLImageElement
                          ).src = `https://www.google.com/s2/favicons?domain=${n.domain}&sz=128`;
                        }}
                      />
                    ) : (
                      <div className="flex h-full w-full items-center justify-center">
                        <div className="text-center">
                          <svg
                            className="w-8 h-8 mx-auto text-slate-400 mb-2"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={1.5}
                              d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
                            />
                          </svg>
                          <span className="text-xs text-slate-400 font-medium">
                            No preview
                          </span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Text */}
                <div className="line-clamp-2 text-sm font-bold text-slate-800 leading-snug mb-2">
                  {n.title}
                </div>
                <div className="text-xs text-slate-500 font-medium mb-3 truncate">
                  {n.domain}
                </div>
                <div className="flex items-center justify-between">
                  <a
                    href={n.url}
                    target="_blank"
                    className="btn-gradient rounded-xl px-4 py-2 text-xs font-semibold text-white hover:scale-105 transition-all duration-200 shadow-md flex items-center gap-2"
                  >
                    <svg
                      className="w-3 h-3"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                      />
                    </svg>
                    Open
                  </a>
                  <div className="flex items-center gap-2">
                    {isUpdatingPosition === n.id && (
                      <LoadingSpinner size="sm" />
                    )}
                    {isEnriching === n.id && <LoadingSpinner size="sm" />}
                    <span className="rounded-xl bg-slate-100/80 px-3 py-1.5 text-xs text-slate-600 font-medium backdrop-blur-sm">
                      <svg
                        className="w-3 h-3 inline mr-1"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
                        />
                      </svg>
                      Drag
                    </span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Clustering Suggestions Dialog */}
      <ClusteringSuggestionsDialog
        isOpen={isClusteringDialogOpen}
        onClose={() => setIsClusteringDialogOpen(false)}
        suggestions={clusterSuggestions}
        isLoading={isLoadingSuggestions}
        onAcceptSuggestion={acceptClusterSuggestion}
        onRefreshSuggestions={loadClusterSuggestions}
      />

      {/* Confirmation Dialog */}
      <ConfirmationDialog
        isOpen={confirmDialog.isOpen}
        onClose={() => setConfirmDialog((prev) => ({ ...prev, isOpen: false }))}
        onConfirm={confirmDialog.onConfirm}
        title={confirmDialog.title}
        description={confirmDialog.description}
        confirmText="Delete"
        cancelText="Cancel"
        variant="destructive"
      />
    </div>
  );
}
